version: "3"

services:

  #PHP FPM Container
  php-fpm:
    container_name: ${PROJECT_NAMESPACE}_php_fpm
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    restart: unless-stopped
    volumes:
      - ./source_code:${PROJECT_ROOT}
    environment:
      - VERBOSE=false
    networks:
      - magento2_dev

  #NGINX Container
  nginx:
    container_name: ${PROJECT_NAMESPACE}_nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - ./source_code:${PROJECT_ROOT}
    ports:
      - 80:80
      - 443:443
    networks:
      - magento2_dev
    links:
      - php-fpm

  


networks:
  magento2_dev:
    driver: bridge

