version: "3"

services:

  #PHP FPM Container
  php-fpm:
    container_name: ${PROJECT_NAMESPACE}_php_fpm
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    restart: unless-stopped
    volumes:
      - ./source_code:${PROJECT_ROOT}
    environment:
      - VERBOSE=false
    networks:
      - magento2_dev

  #PHP CLI Container
  php-cli:
    container_name: ${PROJECT_NAMESPACE}_php_cli
    build:
      context: .
      dockerfile: .docker/php-cli/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    restart: unless-stopped
    volumes:
      - ./source_code:${PROJECT_ROOT}
    environment:
      - VERBOSE=false
    networks:
      - magento2_dev
    tty: true

  #PHP Cron Job Container
  php-cron:
    container_name: ${PROJECT_NAMESPACE}_php_cron
    build:
      context: .
      dockerfile: .docker/php-cron/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    restart: unless-stopped
    volumes:
      - ./source_code:${PROJECT_ROOT}
    networks:
      - magento2_dev
    environment:
      - VERBOSE=false

  #NGINX Container
  nginx:
    container_name: ${PROJECT_NAMESPACE}_nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
      args:
        - NGINX_PORT=${NGINX_PORT}
        - NGINX_PROXY=${NGINX_PROXY}
        - PROJECT_URL=${PROJECT_URL}
        - PROJECT_DOMAIN=${PROJECT_DOMAIN}
        - PROJECT_ROOT=${PROJECT_ROOT}
        - TIME_ZONE=${TIME_ZONE}
    restart: unless-stopped
    volumes:
      - ./source_code:${PROJECT_ROOT}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - magento2_dev
    links:
      - php-fpm

networks:
  magento2_dev:
    driver: bridge

