version: "3"

services:

  #NGINX Container
  nginx:
    container_name: ${PROJECT_NAMESPACE}_nginx
    hostname:       ${PROJECT_NAMESPACE}_nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
      args:
        - PROJECT_DOMAIN=${PROJECT_DOMAIN}
    restart: unless-stopped
    volumes:
      - ./source_code:${PROJECT_ROOT}
    environment:
      - NGINX_UNSECURE_PORT=${NGINX_UNSECURE_PORT}
      - NGINX_SECURE_PORT=${NGINX_SECURE_PORT}
      - NGINX_FORCE_SSL=${NGINX_FORCE_SSL}
      - PROJECT_URL=${PROJECT_URL}
      - PROJECT_DOMAIN=${PROJECT_DOMAIN}
      - PROJECT_ROOT=${PROJECT_ROOT}
      - VERBOSE=true
    ports:
      - ${NGINX_UNSECURE_PORT}:80
      - ${NGINX_SECURE_PORT}:443
    networks:
      - magento2_dev


networks:
  magento2_dev:
    driver: bridge

