version: "3"

services:
  ######################################################################################################################
  ### PHP FPM Container
  ######################################################################################################################
  php-fpm:
    container_name: ${PROJECT_NAMESPACE}_php_fpm
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    restart: unless-stopped
    volumes:
      - ./source_code:${PROJECT_ROOT}
    env_file:
      - .env
    networks:
      - magento2_dev
    links:
      - mysql
      - redis-cache
      - redis-page-cache
      - redis-session
  ######################################################################################################################
  ### PHP CLI Container
  ######################################################################################################################
  php-cli:
    container_name: ${PROJECT_NAMESPACE}_php_cli
    build:
      context: .
      dockerfile: .docker/php-cli/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    restart: unless-stopped
    volumes:
      - ./source_code:${PROJECT_ROOT}
    env_file:
      - .env
    networks:
      - magento2_dev
    tty: true
    links:
      - mysql
      - redis-cache
      - redis-page-cache
      - redis-session
  ######################################################################################################################
  ### PHP Cron Job Container
  ######################################################################################################################
  php-cron:
    container_name: ${PROJECT_NAMESPACE}_php_cron
    build:
      context: .
      dockerfile: .docker/php-cron/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    restart: unless-stopped
    volumes:
      - ./source_code:${PROJECT_ROOT}
    networks:
      - magento2_dev
    links:
      - mysql
      - redis-cache
      - redis-page-cache
      - redis-session
    env_file:
      - .env
  ######################################################################################################################
  ### NGINX Container
  ######################################################################################################################
  nginx:
    container_name: ${PROJECT_NAMESPACE}_nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
      args:
        - NGINX_PORT=${NGINX_PORT}
        - NGINX_PROXY=${NGINX_PROXY}
        - PROJECT_URL=${PROJECT_URL}
        - PROJECT_DOMAIN=${PROJECT_DOMAIN}
        - PROJECT_ROOT=${PROJECT_ROOT}
        - TIME_ZONE=${TIME_ZONE}
    restart: unless-stopped
    volumes:
      - ./source_code:${PROJECT_ROOT}
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - magento2_dev
    links:
      - php-fpm
  ######################################################################################################################
  ### Database Container
  ######################################################################################################################
  mysql:
    container_name: ${PROJECT_NAMESPACE}_mysql
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env
    networks:
      - magento2_dev
  ######################################################################################################################
  ### Database Management Container
  ######################################################################################################################
  phpmyadmin:
    container_name: ${PROJECT_NAMESPACE}_phpmyadmin
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8888:80"
    depends_on:
      - mysql
    networks:
      - magento2_dev
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
  ######################################################################################################################
  ### Redis Container for default cache
  ######################################################################################################################
  redis-cache:
    container_name: ${PROJECT_NAMESPACE}_redis_cache
    build:
      context: .
      dockerfile: .docker/redis/Dockerfile
      args:
        - ALPINE_VERSION=${ALPINE_VERSION}
    restart: unless-stopped
    volumes:
      - redis-cache:/data
    env_file:
      - .env
    networks:
      - magento2_dev
    tty: true
  ######################################################################################################################
  ### Redis Container for full page cache
  ######################################################################################################################
  redis-page-cache:
    container_name: ${PROJECT_NAMESPACE}_redis_page_cache
    build:
      context: .
      dockerfile: .docker/redis/Dockerfile
      args:
        - ALPINE_VERSION=${ALPINE_VERSION}
    restart: unless-stopped
    volumes:
      - redis-page-cache:/data
    env_file:
      - .env
    networks:
      - magento2_dev
    tty: true
  ######################################################################################################################
  ### Redis Container for session
  ######################################################################################################################
  redis-session:
    container_name: ${PROJECT_NAMESPACE}_redis_session
    build:
      context: .
      dockerfile: .docker/redis/Dockerfile
      args:
        - ALPINE_VERSION=${ALPINE_VERSION}
    restart: unless-stopped
    volumes:
      - redis-session:/data
    env_file:
      - .env
    networks:
      - magento2_dev
    tty: true
  ######################################################################################################################
  ### Varnish Proxy Container
  ######################################################################################################################
  varnish:
    container_name: ${PROJECT_NAMESPACE}_varnish
    build:
      context: .
      dockerfile: .docker/varnish/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - magento2_dev
    links:
      - nginx
    ports:
      - "80:80"
  ######################################################################################################################
  ### RabbitMQ Messaging Queuing System
  ######################################################################################################################
  rabbitmq:
    container_name: ${PROJECT_NAMESPACE}_rabbitmq
    image: rabbitmq:3.7.8-management
    volumes:
      - 'rabbitmq_data:/data'
    environment:
      - RABBITMQ_DEFAULT_USER=${MAGENTO_AMQP_USER}
      - RABBITMQ_DEFAULT_PASS=${MAGENTO_AMQP_PASSWORD}
    networks:
      - magento2_dev
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
  ######################################################################################################################
  ### ElasticSearch Container
  ######################################################################################################################
  elasticsearch:
    container_name: ${PROJECT_NAMESPACE}_elasticsearch
    build:
      context: .
      dockerfile: .docker/elasticsearch/Dockerfile
    restart: unless-stopped
    volumes:
      - .docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - magento2_dev
  ######################################################################################################################
  ### LogStash Container
  ######################################################################################################################
  logstash:
    container_name: ${PROJECT_NAMESPACE}_logstash
    build:
      context: .
      dockerfile: .docker/logstash/Dockerfile
    ports:
      - 12201:12201/udp
      - 5000:5000
      - 5044:5044
      - 9600:9600
    volumes:
      - .docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - .docker/logstash/pipeline/:/usr/share/logstash/pipeline:ro
    networks:
      - magento2_dev
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  ######################################################################################################################
  ### filebeat Container
  ######################################################################################################################
  filebeat:
    container_name: ${PROJECT_NAMESPACE}_filebeat
    build:
      context: .
      dockerfile: .docker/filebeat/Dockerfile
    volumes:
      - .docker/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - /var/log/:/var/log/:ro
    networks:
      - magento2_dev
    links:
      - logstash
    depends_on:
      - elasticsearch
  ######################################################################################################################
  ### Kibana Container
  ######################################################################################################################
  kibana:
    container_name: ${PROJECT_NAMESPACE}_kibana
    build:
      context: .
      dockerfile: .docker/kibana/Dockerfile
    ports:
      - 5601:5601
    volumes:
      - .docker/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - magento2_dev
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  ######################################################################################################################
  ### MailHog for Email Catching System
  ######################################################################################################################
  mailhog:
    container_name: ${PROJECT_NAMESPACE}_mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - magento2_dev
########################################################################################################################
### Volumes Containers
########################################################################################################################
volumes:
  database:
  redis-cache:
  redis-page-cache:
  redis-session:
  rabbitmq_data:
  elasticsearch:
########################################################################################################################
### Networks
########################################################################################################################
networks:
  magento2_dev:
    driver: bridge