version: "3"

services:
  #NGINX Container
  nginx:
    container_name: ${PROJECT_NAMESPACE}_nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - ./source_code:${PROJECT_ROOT}
    ports:
      - 80:80
      - 443:443
    networks:
      - magento2_dev
    depends_on:
      - php-fpm

  


networks:
  magento2_dev:
    driver: bridge

